const users = require('./users/users.service.js');
const colors = require('./colors/colors.service.js');
const packageTypes = require('./package-types/package-types.service.js');
const stockGroups = require('./stock-groups/stock-groups.service.js');
const stockItems = require('./stock-items/stock-items.service.js');
const stockItemTransactions = require('./stock-item-transactions/stock-item-transactions.service.js');
const coldRoomTemperatures = require('./cold-room-temperatures/cold-room-temperatures.service.js');
const vehicleTemperatures = require('./vehicle-temperatures/vehicle-temperatures.service.js');
const suppliers = require('./suppliers/suppliers.service.js');
const people = require('./people/people.service.js');
const cities = require('./cities/cities.service.js');
const countries = require('./countries/countries.service.js');
const deliveryMethods = require('./delivery-methods/delivery-methods.service.js');
const stateProvinces = require('./state-provinces/state-provinces.service.js');
const supplierCategories = require('./supplier-categories/supplier-categories.service.js');
const languages = require('./languages/languages.service.js');
const images = require('./images/images.service.js');
const uploads = require('./uploads/uploads.service.js');
const media = require('./media/media.service.js');
const customers = require('./customers/customers.service.js');
const addresses = require('./addresses/addresses.service.js');
const addressTypes = require('./address-types/address-types.service.js');
const buyingGroups = require('./buying-groups/buying-groups.service.js');
const customerCategories = require('./customer-categories/customer-categories.service.js');
const customerTransactions = require('./customer-transactions/customer-transactions.service.js');
const invoices = require('./invoices/invoices.service.js');
const invoiceLines = require('./invoice-lines/invoice-lines.service.js');
const orderTracking = require('./order-tracking/order-tracking.service.js');
const receipts = require('./receipts/receipts.service.js');
const orders = require('./orders/orders.service.js');
const orderLines = require('./order-lines/order-lines.service.js');
const categories = require('./categories/categories.service.js');
const subcategories = require('./subcategories/subcategories.service.js');
const classifications = require('./classifications/classifications.service.js');
const customRunner = require('./custom-runner/custom-runner.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(users);
  app.configure(colors);
  app.configure(packageTypes);
  app.configure(stockGroups);
  app.configure(stockItems);
  app.configure(stockItemTransactions);
  app.configure(coldRoomTemperatures);
  app.configure(vehicleTemperatures);
  app.configure(suppliers);
  app.configure(people);
  app.configure(cities);
  app.configure(countries);
  app.configure(deliveryMethods);
  app.configure(stateProvinces);
  app.configure(supplierCategories);
  app.configure(languages);
  app.configure(images);
  app.configure(uploads);
  app.configure(media);
  app.configure(customers);
  app.configure(addresses);
  app.configure(addressTypes);
  app.configure(buyingGroups);
  app.configure(customerCategories);
  app.configure(customerTransactions);
  app.configure(invoices);
  app.configure(invoiceLines);
  app.configure(orderTracking);
  app.configure(receipts);
  app.configure(orders);
  app.configure(orderLines);
  app.configure(categories);
  app.configure(subcategories);
  app.configure(classifications);
  app.configure(customRunner);
};
